### PR TITLE
UI redesigning of the website is done

### LINKED ISSUE #88: About page is missing 😞 and UI design can be improved of the home page as well
I can **add about page** as well as can improve the all-over **UI design** of the home page keeping in mind the consistency of the home page and about page 😄 @shivshankar9

### PR DESCRIPTION
**Pull request by devikavarshney**
https://devikavarshney.github.io/Student-portal/

### CODE REVIEW

**Comment by aakankshabhende** [comment]
Commendable work🎉 @devikavarshney 
But can you please put some pic or effect related to our project in the background instead of black colour.

**Comment by devikavarshney** [comment]
@aakankshabhende I didn't get you what type of pictures ? Can you give example ?

**Comment by aakankshabhende** [comment]
Any abstract background like small patterns

**Comment by devikavarshney** [comment]
@aakankshabhende okay you mean any illustrations or something because it is looking very simple. Right ?

**Comment by aakankshabhende** [comment]
Yes

**Comment by devikavarshney** [comment]
@aakankshabhende I have a request if you can change the it from easy to medium because I designed the logo too on figma myself and added animations.

**Comment by devikavarshney** [comment]
image
<br> <br>
image
<br>
@aakankshabhende check this.

**Comment by aakankshabhende** [comment]
> @aakankshabhende I have a request if you can change the it from easy to medium because I designed the logo too on figma myself and added animations.

yes sure @devikavarshney! You did a great work 💫

**Review by aakankshabhende — APPROVED** [review]

**Comment by devikavarshney** [comment]
@aakankshabhende Thank you so much and also I have a question about second approval who will do that and in how many days ?

**Comment by devikavarshney** [comment]
@swati2603 can you approve this PR?

**Comment by aakankshabhende** [comment]
> @aakankshabhende Thank you so much and also I have a question about second approval who will do that and in how many days ?

Soon they will approve

**Comment by devikavarshney** [comment]
@swati2603 @saikatmu31 please give approval to this PR.

**Review by shivshankar9 — APPROVED** [review]

**Review by shivshankar9 — APPROVED** [review]

**Comment by devikavarshney** [comment]
@shivshankar9 Thank you so much for merging the PR

**Pull request merged**
