### PR TITLE
Enhanced and Validated the Contact-Form

### PR DESCRIPTION
**Pull request by SarandeepSingh17**
Validated the Contact Form for E-Mail, Name using JavaScript, slight changes in the layout of Contact Form.
image

### CODE REVIEW

**Comment by shivshankar9** [comment]
Is that responsive, 
provide GitHub page link

**Comment by SarandeepSingh17** [comment]
No, it is not responsive
I'll work on that

**Comment by SarandeepSingh17** [comment]
I have made the desired changes

**Comment by Abirpal202049** [comment]
At first pull the latest changes and then add your validations other wise it will broke the code. So, make the changes by pulling the latest changes. For any dout contact us on Discord

**Pull request closed without merging**
