### PR TITLE
Separate tools heading and items

### LINKED ISSUE #41: Changes in tools
I would like to put the tools heading and tool items(rows) in different blocks so that we can apply CSS to them separately.

### PR DESCRIPTION
**Pull request by abaran803**
@shivshankar9  Please check the changes and review them.

### CODE REVIEW

**Comment by shivshankar9** [comment]
Add screenshot or share page link

**Comment by shivshankar9** [comment]
Remove center heading add function buttons for every tools in center,

**Comment by abaran803** [comment]
> Add screenshot or share page link

There is no change in the view of the page, it is a change in the arrangement of the HTML elements. It is helpful when applying CSS in this section.

**Comment by abaran803** [comment]
> Remove center heading add function buttons for every tools in center,

Not getting "function buttons". Are you talking about adding a button to every tool, so that they execute some JavaScript function? Also not getting tools in center.

**Comment by shivshankar9** [comment]
> > Remove center heading add function buttons for every tools in center,
> 
> Not getting "function buttons". Are you talking about adding a button to every tool, so that they execute some JavaScript function? Also not getting tools in center.

Yes, add Page link or screenshot here

**Comment by abaran803** [comment]
> > > Remove center heading add function buttons for every tools in center,
> > 
> > 
> > Not getting "function buttons". Are you talking about adding a button to every tool, so that they execute some JavaScript function? Also not getting tools in center.
> 
> Yes, add Page link or screenshot here

I'm using it on my local system, by localhost. How can I share a link?
temp4
Screenshot, after removing center heading.

**Comment by shivshankar9** [comment]
> > > > Remove center heading add function buttons for every tools in center,
> > > 
> > > 
> > > Not getting "function buttons". Are you talking about adding a button to every tool, so that they execute some JavaScript function? Also not getting tools in center.
> > 
> > 
> > Yes, add Page link or screenshot here
> 
> I'm using it on my local system, by localhost. How can I share a link? temp4 Screenshot, after removing center heading.

GitHub provides page link where u can host your branch and share link ,

**Comment by shivshankar9** [comment]
I mean that change styling for those buttons

**Comment by abaran803** [comment]
> > > > > Remove center heading add function buttons for every tools in center,
> > > > 
> > > > 
> > > > Not getting "function buttons". Are you talking about adding a button to every tool, so that they execute some JavaScript function? Also not getting tools in center.
> > > 
> > > 
> > > Yes, add Page link or screenshot here
> > 
> > 
> > I'm using it on my local system, by localhost. How can I share a link? temp4 Screenshot, after removing center heading.
> 
> GitHub provides page link where u can host your branch and share link ,

Ok

**Comment by abaran803** [comment]
> > > > > > Remove center heading add function buttons for every tools in center,
> > > > > 
> > > > > 
> > > > > Not getting "function buttons". Are you talking about adding a button to every tool, so that they execute some JavaScript function? Also not getting tools in center.
> > > > 
> > > > 
> > > > Yes, add Page link or screenshot here
> > > 
> > > 
> > > I'm using it on my local system, by localhost. How can I share a link? temp4 Screenshot, after removing center heading.
> > 
> > 
> > GitHub provides page link where u can host your branch and share link ,
> 
> Ok

Here's the link: https://abaran803.github.io/Student-portal/

**Comment by abaran803** [comment]
> I mean that change styling for those buttons

temp5
Is this the change you are talking about?

**Comment by shivshankar9** [comment]
> > I mean that change styling for those buttons
> 
> temp5
> 
> Is this the change you are talking about?

Yes do something unique, and also ui should be responsive on other devices as well

**Comment by abaran803** [comment]
> > > I mean that change styling for those buttons
> > 
> > 
> > temp5
> > Is this the change you are talking about?
> 
> Yes do something unique, and also ui should be responsive on other devices as well

Can I use flexbox and media query here for responsiveness

**Comment by abaran803** [comment]
Please check if the tools part is responsive
Link: https://abaran803.github.io/Student-portal/

**Comment by shivshankar9** [comment]
> Please check if the tools part is responsive Link: https://abaran803.github.io/Student-portal/

Nav-bar not responsive can you that

**Comment by abaran803** [comment]
> > Please check if the tools part is responsive Link: https://abaran803.github.io/Student-portal/
> 
> Nav-bar not responsive can you that

Yeah. But for me, it will take time.

**Comment by abaran803** [comment]
> > > Please check if the tools part is responsive Link: https://abaran803.github.io/Student-portal/
> > 
> > 
> > Nav-bar not responsive can you that
> 
> Yeah. But for me, it took time.

But as I saw, someone it already working on a navbar issue, should I do it.

**Comment by abaran803** [comment]
@shivshankar9 Thanks for merging PR. I have created a different issue #42 , which is about width of heading, which is not responsive. Please check this.

**Comment by shivshankar9** [comment]
> Please check if the tools part is responsive Link: https://abaran803.github.io/Student-portal/



> @shivshankar9 Thanks for merging PR. I have created a different issue #42 , which is about width of heading, which is not responsive. Please check this.

Ok sure I ll check,

**Pull request merged**
