### PR TITLE
Text to pdf functionality added

### PR DESCRIPTION
**Pull request by davyj123**
Kind of change this PR introduce :
1. This pr contain changes related to the issue #11  
2. In this pr the text to pdf page is designed.
3. Issue it resolves : Prevoius UI does not contain text to pdf functionaility.
4. Screenshots: 
Screenshot (196)
Designed with
Screenshot (197)

Github Page Link : https://davyj123.github.io/Student-portal/

### CODE REVIEW

**Review by swati2603 — APPROVED** [review]

**Comment by swati2603** [comment]
@davyj123 Welldone.

**Comment by davyj123** [comment]
Thank you mam

**Comment by swati2603** [comment]
@davyj123 You can call me Swati and keep it up :)

**Comment by davyj123** [comment]
Ok @swati2603

**Review by shivshankar9 — APPROVED** [review]

**Pull request merged**
