### PR TITLE
fixes issue #110

### LINKED ISSUE #110: add logo to nav

### PR DESCRIPTION
**Pull request by geetika005**
Please review it

### CODE REVIEW

**Comment by aakankshabhende** [comment]
@geetika005 can you please add a little bit of left margin

**Comment by geetika005** [comment]
Is it ok now

**Comment by aakankshabhende** [comment]
Please put a screenshot

**Comment by aakankshabhende** [comment]
Great work :) @geetika005

**Review by aakankshabhende — APPROVED** [review]

**Review by shivshankar9 — APPROVED** [review]

**Pull request merged**
