### PR TITLE
Added logo

### LINKED ISSUE #23: Add logo
Create logo and add to homepage

### PR DESCRIPTION
**Pull request by geetika005**
fixes issue:#23

### CODE REVIEW

**Comment by shivshankar9** [comment]
> 
> 
> fixes issue:#23
U have done great job,
But can you try something else unique
Also we looking for new namee so you don't need 
To follow the same logo as name of site,  it can be any design

**Comment by geetika005** [comment]
Please review it.

**Review by shivshankar9 — CHANGES_REQUESTED** [review]
There some conflicts could you resovle it

**Comment by shivshankar9** [comment]
@geetika005

**Comment by geetika005** [comment]
Yes i am working on it

**Comment by geetika005** [comment]
i am unable to see home.css file in the real repository because i think someone is working on it but earlier it was there so now should i just commit the logo image ?

**Comment by geetika005** [comment]
I have uploaded the new logo image sir and deleted the css file as the home page is not ready yet

**Pull request closed without merging**
