### PR TITLE
Service Page created

### PR DESCRIPTION
**Pull request by NamanGokharu**
image

Created a basic service page which can be modified with more facilities after addition.

### CODE REVIEW

**Comment by NamanGokharu** [comment]
It is pending from too long, please do tell changes if any?

**Comment by shivshankar9** [comment]
> It is pending from too long, please do tell changes if any?

Use default nav,

**Comment by NamanGokharu** [comment]
Okay, I will add it on this page.

**Comment by aakankshabhende** [comment]
Any updates? @NamanGokharu

**Comment by NamanGokharu** [comment]
I will complete and submit it by today itself,

**Comment by aakankshabhende** [comment]
Okay no issues @NamanGokharu

**Comment by NamanGokharu** [comment]
image
I have successfully changed the following, and added navbar as said!

**Comment by aakankshabhende** [comment]
Please change the colour to colour scheme of main home page, that is, blue @NamanGokharu

**Comment by shivshankar9** [comment]
> image I have successfully changed the following, and added navbar as said!

U don't need to change just u use default theme

**Comment by Abirpal202049** [comment]
@NamanGokharu have you done your changes otherwise we had to assing this to others

**Comment by NamanGokharu** [comment]
done with the changes, will be uploading today

**Comment by NamanGokharu** [comment]
image
Did the service page with css similar to home page as said

**Comment by NamanGokharu** [comment]
Anything else to go on with as of now,

**Comment by shivshankar9** [comment]
> done with the changes, will be uploading today

resolve conflicting files and make sure that you are not Creating PR from main branch.

**Comment by NamanGokharu** [comment]
resolved all conflicts as said! into sub branch...

**Comment by swati2603** [comment]
> resolved all conflicts as said! into sub branch...

Can you share the link?

**Comment by NamanGokharu** [comment]
I just checked in a while, going on with MTTs, btw Which link, Please elaborate?

**Comment by swati2603** [comment]
> I just checked in a while, going on with MTTs, btw Which link, Please elaborate?

Host it on your github and share the link here.

**Comment by NamanGokharu** [comment]
https://namangokharu.github.io/Student-portal/index.html

**Comment by swati2603** [comment]
> https://namangokharu.github.io/Student-portal/index.html
I'm creating another issue you may work on that.

**Pull request closed without merging**
