### PR TITLE
Proper alignment of about section and home page edit.

### PR DESCRIPTION
**Pull request by Bikramjit21**
### What kind of change does this PR introduce ?

Edited different sections.

### Documentation updated ?

No

### Checklist

- [*] I have performed a self-review of my own code
- [*] I have commented my code, particularly in hard-to-understand areas
- [*] I have made corresponding changes to the documentation
- [*] My changes generate no new warnings
- [*] I have added tests that prove my fix is effective or that my feature works
- [*] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by aakankshabhende** [comment]
@Bikramjit21 can you please put the link of your GitHub page

**Comment by Bikramjit21** [comment]
@aakankshabhende I have to host it in github page further?

**Comment by aakankshabhende** [comment]
Yes just to check what changes you have done @Bikramjit21

**Comment by Bikramjit21** [comment]
student home
student about

This two portions.

**Pull request closed without merging**
