### PR TITLE
user defined filename feature added in Text-to-pdf tool.

### PR DESCRIPTION
**Pull request by siva-krish45**
### What kind of change does this PR introduce ?
#156 
This PR introduces a new feature. The feature is about giving use rdefined filename to the pdf u get to download from the Text-to-pdf tool.

### Documentation updated ?

No

### Checklist

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Links

check out the new feature in this link https://siva-krish45.github.io/Student-portal/Text-to-pdf/index.html

## Screenshots

Intro page:

image

The file downloaded was subjects.pdf as mentioned in the filename input field.

image

it also checks whether the filename is valid and gives an message.

image

download pdf button is only enabled when both the fields are non empty and valid.

### CODE REVIEW

**Review by swati2603 — APPROVED** [review]

**Comment by swati2603** [comment]
@siva-krish45 Are you participating in SWOC'21? 
If yes, then tell me your Participant Id.

**Comment by siva-krish45** [comment]
@swati2603 i am not participating in SWOC'21. is it possible to join now ?

**Comment by swati2603** [comment]
> @swati2603 i am not participating in SWOC'21. is it possible to join now ?
According to my, I think you can't. Since it has been a month, it has already started. But I'll ask and tell you.

**Comment by siva-krish45** [comment]
> > @swati2603 i am not participating in SWOC'21. is it possible to join now ?
> > According to my, I think you can't. Since it has been a month, it has already started. But I'll ask and tell you.

yeah sure.

**Comment by aakankshabhende** [comment]
@siva-krish45 Participant registration for swoc'21 are  closed

**Review by aakankshabhende — APPROVED** [review]

**Comment by siva-krish45** [comment]
> @siva-krish45 Participant registration for swoc'21 are  closed

It's okay. No problem

**Pull request merged**
