### PR TITLE
Added word to pdf functionality

### LINKED ISSUE #7: Pdf converter

### PR DESCRIPTION
**Pull request by udith51**
Fixes #7 

The code here converts word to html and then finally html to pdf. This pdf is then saved to local system on user action.
The HTML and JS files are present under **Word-to-Pdf** folder.

**Walkthrough:**

image

image

image

**Sample Input Word doc:**
[Google LLC.docx](https://github.com/shivshankar9/Student-portal/files/7774035/Google.LLC.docx)

**Converted Pdf using our website:**
[myfile (13).pdf](https://github.com/shivshankar9/Student-portal/files/7774042/myfile.13.pdf)

**Git Page**
https://udith51.github.io/Student-portal/Word-to-Pdf/index.html

### CODE REVIEW

**Review by Abirpal202049 — CHANGES_REQUESTED** [review]
Link the stylesheet don't add css in Html

**Comment by udith51** [comment]
The css file required for word-to-pdf conversion has been separated from html file.

**Comment by Abirpal202049** [comment]
First of all host your website on your github and give the link. So that we can verify weather its working or not. and also make the changes as per the new file structure. And match the theme with the home bage and for any dout contact us on Discord

**Comment by udith51** [comment]
@Abirpal202049, would surely do that but I asked the project admin, he said to add just the functionality for now. After this pr is accepted, create another issue to update the theme and there work for the theme.

**Comment by Abirpal202049** [comment]
@udith51 Just do one thing put your index.html file outside the Word-to-Pdf folder and link that for any dout feel free to contact

**Comment by shivshankar9** [comment]
Its working fine, just link nav file and move the functions buttons to centre @udith51

**Comment by udith51** [comment]
@shivshankar9 , Thanks!
I have linked it to our main page and centered the content. You may check now!

**Comment by udith51** [comment]
@Abirpal202049, Sorry but I couldn't get you. Like if I put my index.html outside Word-to-Pdf, won't it be a conflict with the file structure because what I initially perceived the idea of our file structure is that for each functionality we have different folder, and we link it with main page(present at /root). Doc-to-Word conversion being a functionality, I added it inside a folder.
I am new to Open Source. So it would be a ton of help if you could guide me here🥲😅

**Comment by shivshankar9** [comment]
@udith51 Can you provide deployed GitHub page link

**Comment by udith51** [comment]
@Abirpal202049 since you asked for the link, I have hosted it and here it is: https://udith51.github.io/Student-portal/Word-to-Pdf/index.html so that you may verify the functionality.
You may also check it through https://udith51.github.io/Student-portal and then click on Document to Pdf button.
Thanks!

**Comment by udith51** [comment]
@shivshankar9 Here it is: https://udith51.github.io/Student-portal/Word-to-Pdf/index.html

**Comment by shivshankar9** [comment]
Ui improvements needed,

**Comment by udith51** [comment]
Hey @shivshankar9, after closing this issue we can create another one for Ui to sync with main page theme.
https://github.com/shivshankar9/Student-portal/issues/7#issuecomment-998984694
https://github.com/shivshankar9/Student-portal/issues/7#issuecomment-999438973
Should we?

**Comment by Abirpal202049** [comment]
Then let's merge this PR and create another issue for improving thr UI

**Comment by udith51** [comment]
Yeah, that would be great! @Abirpal202049

**Review by shivshankar9 — APPROVED** [review]

**Review by Abirpal202049 — APPROVED** [review]

**Pull request merged**
