### PR TITLE
Changes in contact page

### PR DESCRIPTION
**Pull request by geetika005**
fixes issue#126
Github page link -https://geetika005.github.io/Student-portal/

Screenshot

### CODE REVIEW

**Comment by geetika005** [comment]
@aakankshabhende @Abirpal202049 please review this

**Comment by Abirpal202049** [comment]
Can you make the contact page responsive

**Review by Abirpal202049 — CHANGES_REQUESTED** [review]
Try to make it responsive

**Comment by geetika005** [comment]
> Try to make it responsive

Ok

**Comment by swati2603** [comment]
image
This field is also accepting content other than mail. Try to fix it so that only mail IDs will be accepted. Same with other fields too.

**Comment by geetika005** [comment]
Ok

**Comment by geetika005** [comment]
@swati2603 @Abirpal202049  please review the changes

**Review by Abirpal202049 — APPROVED** [review]

**Review by swati2603 — APPROVED** [review]

**Pull request merged**
