### PR TITLE
Added img-to-pdf functionality

### LINKED ISSUE #10: Images to pdf
Add functionality to convert img to pdf

### PR DESCRIPTION
**Pull request by Korra15**
Fixes #10 
Added the image to pdf conversion functionality using python.
The packges used in the program are listed in the requirements.txt file.

### CODE REVIEW

**Comment by shivshankar9** [comment]
> Fixes #10 Added the image to pdf conversion functionality using python. The packges used in the program are listed in the requirements.txt file.

Can u add it to home page

**Comment by Korra15** [comment]
The information regarding this should be added on the home page? Or something else is the requirement?

**Comment by shivshankar9** [comment]
> The information regarding this should be added on the home page? Or something else is the requirement?

You can add it accordingly
Or else you can create another basic page for specific function and add there,
It should be working properly..

**Comment by Korra15** [comment]
okay

**Pull request merged**
