### PR TITLE
Updated the tool section

### PR DESCRIPTION
**Pull request by tiasaxena**
finalscreen
The updated screen snap is attached above :)

### CODE REVIEW

**Comment by shivshankar9** [comment]
Could please resolve the conflicts

**Comment by tiasaxena** [comment]
Hey, can I please be informed about this merge conflict issue? I am a novice to GitHub and certainly, I did not get what this means and how to resolve this? @shivshankar9

**Comment by shivshankar9** [comment]
> Hey, can I please be informed about this merge conflict issue? I am a novice to GitHub and certainly, I did not get what this means and how to resolve this? @shivshankar9

You need to update repository code,
If u face any issue just dm me or mentors in discord

**Review by shivshankar9 — CHANGES_REQUESTED** [review]
..

**Review by shivshankar9 — APPROVED** [review]

**Pull request merged**
