### PR TITLE
Update homepage.css

### PR DESCRIPTION
**Pull request by dassoumyamoy00**
Whenever we are hovering on the respective services, the background color is getting changed to purple, same as the text color. So the text is not at all visible. This might degrade user experience. Hence I have made a tiny change, updated the text color to white on hovering.

### CODE REVIEW

**Comment by aakankshabhende** [comment]
Can you please put the screenshots here @dassoumyamoy00

**Comment by dassoumyamoy00** [comment]
>

**Comment by dassoumyamoy00** [comment]
> Can you please put the screenshots here @dassoumyamoy00

U can get yourself viewed also, upon hovering the entire box is getting purple and no text is visible.

**Comment by shivshankar9** [comment]
Please create PR from seperate branch, and also provide hosted GitHub page link, @dassoumyamoy00

**Pull request closed without merging**
