### PR TITLE
email is now working

### PR DESCRIPTION
**Pull request by bhavikakaura**
### Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Links

Please add github page link,

## Screenshots

Please add appropriate screenshots.

### CODE REVIEW

**Review by aakankshabhende — APPROVED** [review]

**Comment by aakankshabhende** [comment]
Good work :) @bhavikakaura

**Review by swati2603 — APPROVED** [review]

**Comment by bhavikakaura** [comment]
> 

its showing "This branch has conflicts that must be resolved
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.
Conflicting files "
do I need to again pull to get marks ?

**Comment by aakankshabhende** [comment]
> > 
> 
> its showing "This branch has conflicts that must be resolved Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests. Conflicting files " do I need to again pull to get marks ?

No just resolve the conflicts to get this PR merged into the main

**Comment by bhavikakaura** [comment]
> > > 
> > 
> > 
> > its showing "This branch has conflicts that must be resolved Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests. Conflicting files " do I need to again pull to get marks ?
> 
> No just resolve the conflicts to get this PR merged into the main

no pls check

**Pull request merged**
