### PR TITLE
Responsive nav bar

### PR DESCRIPTION
**Pull request by Manoj-14**
### **Responsive nav bar design**
#23 Logo added
#38 Updated nav design
#31 Navbar to Page linkup and creation
**Desktop version Image is added below**
desktop
 
In the Mobile version Menu symbol is made using `div` tag 
and it is shown below
mbl not pressed

When the Menu bar is clicked the `nav` bar is extended which shows all the `nav-links` as shown below
mbl version

### CODE REVIEW

**Comment by shivshankar9** [comment]
Hey can u share GitHub page link

**Review by shivshankar9 — CHANGES_REQUESTED** [review]
There some conflicts please resolve it

**Comment by Manoj-14** [comment]
Should u tell what are the conflicts

**Comment by shivshankar9** [comment]
> Should u tell what are the conflicts

Update your repository

**Comment by abaran803** [comment]
I found one problem in the navbar, it is not responsive on all devices(pixel2, iphone6 etc.). I think setting up screen size 480px in media query will work on all devices.

**Comment by Manoj-14** [comment]
Yeah thanks i will work on it :)

**Pull request closed without merging**
