### PR TITLE
added cross button to robot

### LINKED ISSUE #121: Add cross button to robot
2022-01-07_LI

### PR DESCRIPTION
**Pull request by rishitajain01**
fixes #121

### CODE REVIEW

**Comment by Abirpal202049** [comment]
Host it on your github and share the link here. After that we can merge it

**Review by Abirpal202049 — APPROVED** [review]

**Comment by swati2603** [comment]
@rishitajain01 Good. Do one more change. Make it small. Change the size of the chatbot.

**Comment by rishitajain01** [comment]
> @rishitajain01 Good. Do one more change. Make it small. Change the size of the chatbot.
@swati2603 done..

**Comment by swati2603** [comment]
@rishitajain01 I was talking about this one.
image

Don't change this one. Make it the same size as before. 
image

**Comment by rishitajain01** [comment]
done..please have a look at it..

**Comment by swati2603** [comment]
> done..please have a look at it..

No change.....can you share the screenshot or link?

**Comment by rishitajain01** [comment]
final

**Review by swati2603 — APPROVED** [review]

**Pull request merged**
