### PR TITLE
Updated UI and functionality Img to pdf and doc to pdf - solved issue #165

### LINKED ISSUE #165: Improving Image to Pdf and Doc to Pdf services UI design.
**Is your feature request related to a problem? Please describe.**
The UI design of the services is not consistent with the design of the website.

**Describe the solution you'd like**
I will improve the design of the services page mentioned above.

### PR DESCRIPTION
**Pull request by devikavarshney**
### What kind of change does this PR introduce?

I have changed the UI design of the Img to pdf and doc to pdf page and corrected the functionality of buttons of doc to pdf page.

### Documentation updated ?

yes

### Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Links

https://devikavarshney.github.io/Student-portal/Functionalities/Img-to-Pdf/index.html

https://devikavarshney.github.io/Student-portal/Functionalities/Word-to-Pdf/

## Screenshots

Img to pdf 
<br> <br>
image

<br> <br>
image

<br> <br>
image

<br><br>
image

<br><br>
Doc to pdf 
<br><br>
image
<br><br>
image
<br><br>
image
<br><br>
image

### CODE REVIEW

**Comment by devikavarshney** [comment]
@shivshankar9 @aakankshabhende Please check this PR. solved issue #165

**Review by aakankshabhende — APPROVED** [review]

**Comment by shivshankar9** [comment]
> @shivshankar9 @aakankshabhende Please check this PR. solved issue #165

its overlapping in small screens, can you fix that,
https://devikavarshney.github.io/Student-portal/Functionalities/Img-to-Pdf/index.html

**Comment by devikavarshney** [comment]
@shivshankar9 can you share screenshot so that i can understand better

**Comment by shivshankar9** [comment]
> @shivshankar9 can you share screenshot so that i can understand better

Screenshot (227)
Screenshot (228)

**Comment by devikavarshney** [comment]
@shivshankar9 I was thinking of making new issue for all over-responsivity of the website after completing these four issues if that is okay for you.

**Review by shivshankar9 — APPROVED** [review]

**Pull request merged**
