### PR TITLE
Logo is added to the nav bar and Animation is added to the menu symbol

### LINKED ISSUE #23: Add logo
Create logo and add to homepage

### PR DESCRIPTION
**Pull request by Manoj-14**
#23 logo is added to the nav bar
and adding values to the alt attributes in image tags
making more responsive by making `max-width:650px`
Animation is added to Menu symbol

Git page : https://manoj-14.github.io/Student-portal/

### CODE REVIEW

**Comment by Abirpal202049** [comment]
Add the name 'Student Portal' after the Logo

**Comment by Manoj-14** [comment]
Ok

**Review by aakankshabhende — APPROVED** [review]

**Comment by shivshankar9** [comment]
@Manoj-14 please resolve the conflicts

**Comment by shivshankar9** [comment]
@Manoj-14 ???

**Pull request closed without merging**
