### PR TITLE
Toggle theme functionality implemented in all service pages

### LINKED ISSUE #187: Toogle theme functionality is not working in any of the functionality page

### PR DESCRIPTION
**Pull request by udith51**
### What kind of change does this PR introduce ?

- Fixes #187 
- Implemented UI functionality for all Service pages

### Checklist

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

## Links
https://udith51.github.io/Student-portal/

## Screenshots
(PS: Dark theme and normal theme are shown side-by-side in screenshots)

Image to Pdf page
image

Doc to Pdf page
image

Text to Pdf page
image

Extract Zip page
image

Image Resizer page
image

Do update me, in case any changes are required:)

### CODE REVIEW

**Comment by udith51** [comment]
Hey @aakankshabhende @swati2603 @shivshankar9, you may review this pr.

**Review by aakankshabhende — APPROVED** [review]

**Comment by swati2603** [comment]
@udith51 Have you tried it by running it on a smartphone?

**Comment by udith51** [comment]
> @udith51 Have you tried it by running it on a smartphone?

Yup @swati2603, I checked it just now. The toggle theme functionality is working perfectly fine on smartphone as well.

**Comment by swati2603** [comment]
> > @udith51 Have you tried it by running it on a smartphone?
> 
> Yup @swati2603, I checked it just now. The toggle theme functionality is working perfectly fine on smartphone as well.

Add the screenshots of your smartphone.

**Comment by udith51** [comment]
> > > @udith51 Have you tried it by running it on a smartphone?
> > 
> > 
> > Yup @swati2603, I checked it just now. The toggle theme functionality is working perfectly fine on smartphone as well.
> 
> Add the screenshots of your smartphone.

 @swati2603 check these
 image
 image
 image
 image
 image

**Review by swati2603 — APPROVED** [review]

**Comment by udith51** [comment]
@swati2603 merge conflicts resolved. You may now merge this pr.
Thanks :)

**Pull request merged**
