### PR TITLE
Validated Contact Form Name Field using JavaScript

### PR DESCRIPTION
**Pull request by SarandeepSingh17**
Responsive Contact Form matching with Home theme and validated different fields using JavaScript, provided text-area for Message fiels

### CODE REVIEW

**Comment by SarandeepSingh17** [comment]
https://sarandeepsingh17.github.io/Student-portal/contact.html

**Comment by Abirpal202049** [comment]
It is not responsive. Can you make it?

**Review by saikatmu31 — DISMISSED** [review]

**Review by Abirpal202049 — APPROVED** [review]

**Comment by SarandeepSingh17** [comment]
Can I know where actually the changes are required?

**Comment by Abirpal202049** [comment]
@SarandeepSingh17 make your page comparbile in mobile using 'Media Query'

**Pull request closed without merging**
