### PR TITLE
Navbar activity correction and other changes done

### PR DESCRIPTION
**Pull request by devikavarshney**
### What kind of change does this PR introduce?
I corrected the navigation function of the navbar, the navbar now changes the activity during scrolling as well as clicking.
I changed the light mode UI design of the Contact page.
I changed the light mode UI design of our services section.
I added a toggle button to every service page navbar and corrected the functionality of the navbar on every service page.
Changed the footer animation CSS properties.
Improved the UI design of the cross button of the chatbot.
And solved the issue of overlapping the about and service section and contact page with the navbar. 
Changed CSS properties of the toggle button.
Solved issue #173 

### Documentation updated ?
Yes

### Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Links
https://devikavarshney.github.io/Student-portal/

## Screenshots

image
image
image
image
image
image

<h2> Problem of Overlapping </h2>
image

<h2> After solving </h2>
image

### CODE REVIEW

**Comment by devikavarshney** [comment]
@shivshankar9 @aakankshabhende Please check this PR. Solved #173

**Review by aakankshabhende — APPROVED** [review]

**Comment by devikavarshney** [comment]
thank you @aakankshabhende 😄

**Comment by devikavarshney** [comment]
@swati2603 Please check this PR.

**Review by swati2603 — APPROVED** [review]

**Comment by devikavarshney** [comment]
Thank you @swati2603 😄

**Pull request merged**
