### PR TITLE
improved home page

### LINKED ISSUE #22: improvement of home page
i am working on home page + footer part

### PR DESCRIPTION
**Pull request by leesha19**
Fixes #22

### CODE REVIEW

**Comment by shivshankar9** [comment]
> Fixes #22

Add page link

**Comment by leesha19** [comment]
> > Fixes #22
> 
> Add page link

provide me links please

**Comment by shivshankar9** [comment]
> > > Fixes #22
> > 
> > 
> > Add page link
> 
> provide me links please

i mean deployed page link or screen shot please add here

**Comment by leesha19** [comment]
> > > > Fixes #22
> > > 
> > > 
> > > Add page link
> > 
> > 
> > provide me links please
> 
> i mean deployed page link or screen shot please add here

[file:///C:/Users/Welcome/Desktop/student%20portal/Student-portal-main/PDF-viewer/index%20(2).html](url)

image
image

**Comment by leesha19** [comment]
please leave a review of my work

**Review by shivshankar9 — APPROVED** [review]
Thanks for making this awesome PR..

**Comment by leesha19** [comment]
> Thanks for making this awesome PR..

r uh going to merge it or not??

**Comment by shivshankar9** [comment]
> > Thanks for making this awesome PR..
> 
> r uh going to merge it or not??
Why not,
It will get merged wait for sometime..

**Review by shivshankar9 — CHANGES_REQUESTED** [review]
Sorry, there some conflicts in PR could you please resolve it

**Comment by leesha19** [comment]
> Sorry, there some conflicts in PR could you please resolve it

could you pls define which type of conflicts u r facing

**Comment by shivshankar9** [comment]
> > Sorry, there some conflicts in PR could you please resolve it
> 
> could you pls define which type of conflicts u r facing

Check code there marked line of code
>>>>>> 
======
This type of signs

**Comment by leesha19** [comment]
> > > Sorry, there some conflicts in PR could you please resolve it
> > 
> > 
> > could you pls define which type of conflicts u r facing
> 
> Check code there marked line of code
> 
> > > > > > >
> 
> ====== This type of signs


i think you changed the path of css file i have edited it on html now pls try merging now and if problem continues pls upload a screenshot

**Review by shivshankar9 — CHANGES_REQUESTED** [review]
Still conflicts there,
Go through YouTube tutorial about Conflicts in repo
And resolve it.

**Comment by leesha19** [comment]
> Still conflicts there, Go through YouTube tutorial about Conflicts in repo And resolve it.

ok

**Comment by leesha19** [comment]
> > Still conflicts there, Go through YouTube tutorial about Conflicts in repo And resolve it.
> 
> ok but there is option you can review a particular line of code where you r facing prob

**Comment by shivshankar9** [comment]
> > > Still conflicts there, Go through YouTube tutorial about Conflicts in repo And resolve it.
> > 
> > 
> > ok but there is option you can review a particular line of code where you r facing prob

Update your cloned repository then push changes what u have made

**Comment by leesha19** [comment]
> > > > Still conflicts there, Go through YouTube tutorial about Conflicts in repo And resolve it.
> > > 
> > > 
> > > ok but there is option you can review a particular line of code where you r facing prob
> 
> Update your cloned repository then push changes what u have made

please merge both the file html and css bcoz css file is linked in according to my repo

**Comment by shivshankar9** [comment]
> > > > > Still conflicts there, Go through YouTube tutorial about Conflicts in repo And resolve it.
> > > > 
> > > > 
> > > > ok but there is option you can review a particular line of code where you r facing prob
> > 
> > 
> > Update your cloned repository then push changes what u have made
> 
> please merge both the file html and css bcoz css file is linked in according to my repo

Still Conflicting files,
I couldn't merge until it's get updated
If u facing issue to update repository
Let me know in discord server, we here to help u.

**Review by shivshankar9 — CHANGES_REQUESTED** [review]
..

**Pull request closed without merging**
