### PR TITLE
Testimonials section added

### PR DESCRIPTION
**Pull request by devikavarshney**
### What kind of change does this PR introduce?

Solved #190 
I have added a testimonials section with animation.

### Documentation updated ?
Yes

### Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Links
https://devikavarshney.github.io/Student-portal/

## Screenshots
image
image

### CODE REVIEW

**Comment by devikavarshney** [comment]
@aakankshabhende @swati2603 @shivshankar9 Please check this PR. Solved issue #190

**Comment by swati2603** [comment]
@devikavarshney Run on your smartphone and add the screenshots.

**Comment by devikavarshney** [comment]
@swati2603 Hey I was thinking of making a new issue for responsivity and light mode of testimonials.

**Review by aakankshabhende — APPROVED** [review]

**Comment by swati2603** [comment]
> @swati2603 Hey I was thinking of making a new issue for responsivity and light mode of testimonials.

Okay

**Review by swati2603 — APPROVED** [review]

**Comment by devikavarshney** [comment]
@aakankshabhende @swati2603 Thank you so much 😄

**Pull request merged**
