### PR TITLE
new home theme

### LINKED ISSUE #117: website theme
hey i would like to change the theme of website

### PR DESCRIPTION
**Pull request by leesha19**
hey just changed the theme i think its looking better now also added a footer,here the github page https://leesha19.github.io/Student-portal/index.html
Fixes #117

### CODE REVIEW

**Comment by swati2603** [comment]
@leesha19 Everything is fine but can you make the "About" section a little more attractive?

**Comment by leesha19** [comment]
> @leesha19 Everything is fine but can you make the "About" section a little more attractive?

okay i will try it but is there any conflicts?

**Comment by swati2603** [comment]
@leesha19 No dear, there are no conflicts.

**Comment by leesha19** [comment]
> @leesha19 No dear, there are no conflicts.

please check it now

**Pull request closed without merging**
