### PR TITLE
Responsive Navbar

### LINKED ISSUE #20: Navbar
I think the navbar is needed to be modified, I will modify the navbar

Pls Assign this to me.

### PR DESCRIPTION
**Pull request by TMahato**

### CODE REVIEW

**Comment by shivshankar9** [comment]
> _No description provided._

Add screenshot with description
Or deployed link
U need mention here which issue u have resolved 
Like this -  #issue

**Comment by TMahato** [comment]
Fixes Issue #20
I made the navbar responsive by adding a new js file.

img2

img1

**Comment by shivshankar9** [comment]
> Fixes Issue #20 I made the navbar responsive by adding a new js file.
> 
> img2
> 
> img1

Thanks for making PR
U did really great job,
Keep contributing....

**Comment by leesha19** [comment]
> > Fixes Issue #20 I made the navbar responsive by adding a new js file.
> > img2
> > img1
> 
> Thanks for making PR U did really great job, Keep contributing....

please dont merge this pr for now as a working on home page

**Comment by shivshankar9** [comment]
Sorry, there is some conflicts in this PR unable to merge,

**Comment by shivshankar9** [comment]
> Sorry, there is some conflicts in this PR unable to merge,

Since there is no response I'm closing this PR

**Comment by TMahato** [comment]
Sorry for the late reply, But I couldn't find why there are conflicts.
when I submitted the pr it was showing no conflicts.

How could I know about the conflict?
It will be helpful for next time

**Comment by shivshankar9** [comment]
> Sorry for the late reply, But I couldn't find why there are conflicts. when I submitted the pr it was showing no conflicts.
> 
> How could I know about the conflict? It will be helpful for next time

You need to update your main branch with base branch

**Pull request closed without merging**
