### PR TITLE
Fixed Links Issue

### LINKED ISSUE #134: unable to redirect to about page from another pages
hey @Abirpal202049 @swati2603 Please assign

### PR DESCRIPTION
**Pull request by Atif0604**
Fix : #134 
Hey @Abirpal202049 @swati2603 
please review

### CODE REVIEW

**Comment by Abirpal202049** [comment]
@Atif0604  Share the github link by hosting it on your github

**Comment by Atif0604** [comment]
> @Atif0604 Share the github link by hosting it on your github

https://atif0604.github.io/Student-portal/

@Abirpal202049

**Review by Abirpal202049 — CHANGES_REQUESTED** [review]
Not Working try to fix it

**Comment by Atif0604** [comment]
> Not Working try to fix it

Whats not working can you please specify??
@Abirpal202049

**Comment by Abirpal202049** [comment]
From other pages like Word to Pdf or Image to Pdf it is not navigating to Home or Contact Page

**Comment by Atif0604** [comment]
@Abirpal202049 now it should be working

**Review by saikatmu31 — APPROVED** [review]

**Review by Abirpal202049 — APPROVED** [review]

**Comment by Atif0604** [comment]
You can merge this now
@swati2603 @Abirpal202049

**Pull request merged**
