### PR TITLE
Added Image to PDF

### LINKED ISSUE #119: Img to pdf not working
Img to pdf tool not working
I'll to make it with js from scratch 
it will convert all images to pdf
@aakankshabhende please assign

### PR DESCRIPTION
**Pull request by Atif0604**
Hey @Abirpal202049 
Please Review
Fix : #119

### CODE REVIEW

**Comment by swati2603** [comment]
@Atif0604 Check one more time because in my system logo is not visible(Left side as above). And try it with **PNG to PDF.**

**Comment by Atif0604** [comment]
@swati2603 now you can check

**Comment by swati2603** [comment]
> @swati2603 now you can check

Now it is fine.

**Review by swati2603 — APPROVED** [review]

**Review by Abirpal202049 — APPROVED** [review]

**Comment by Atif0604** [comment]
Please add Label to my issue

**Pull request merged**
